### ISSUE TITLE
Deprecation with Node 20

### ISSUE THREAD

**Issue by jclaveau** [aarcangeli/load-dotenv#35]
Hello,

Your action is considered deprecated with Node 20: "Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: aarcangeli/load-dotenv@v1.0.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/."

Could you please enable `dependabot` or [Renovate](https://github.com/renovatebot/renovate) to avoid this kind of issues?

Thank you for your work!

**Comment by aarcangeli** [comment]
Hi, thank you for your feedback! I’ve updated the action to address the deprecation warning
