### ISSUE TITLE
Variable expansion

### ISSUE THREAD

**Issue by tomekowal** [aarcangeli/load-dotenv#36]
Hi,

Would you consider supporting variable expansion?
AFAIU, it should be enough to replace `dotenv` package with `dotenv-expand` package.
If you are open for it, I can make a PR.

Thanks for this action!

**Comment by aarcangeli** [comment]
Hi, I have updated the action to support the expand field. Could you please confirm if this works for you?

**Comment by tomekowal** [comment]
Hi! Thanks for the update. We've migrated in the meantime to `xom9ikk/dotenv@v2.3.0`, so I won't be able to test at this time.
I'll keep in mind to check it when I have a new project.
